name: Release 

on: 
  push:
    tags:
      - 'v*'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - run: |
              chmod +x ./gradlew
              ./gradlew assembleRelease
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
      - uses: actions/checkout@v1
      - name: Set up Java 
      - uses: actions/setup-java@v1
        with:
          registry-url: https://maven.pkg.github.com
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          java-version: 1.8
      - name: Publish
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew publish