name: Release 

on: 
  push:
    tags:
      - 'v*'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - run: |
              chmod +x ./gradlew
              ./gradlew assembleRelease
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          registry-url: https://maven.pkg.github.com
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          java-version: 1.8
      - run: | 
              ./gradlew :xyo-android-library:assembleRelease
              mvn deploy -Dregistry=https://maven.pkg.github.com/XYOracleNetwork -Dtoken=${{ secrets.GITHUB_TOKEN }}